export default {
    state: {
        enumType: {
            InsurerType: 1, //保险公司类型
            AgentType: 2, //业务渠道
            CommissionPayment: 4, //手续费支付方式
            Province: 6, //省
            City: 7, //市
            TurnAgencyType: 9, //转代理机构类型
            JobGrade: 10, //代理人职级
            SettlementFlag: 11, //结算方式
            dataType: 16, //资料中心类型
            visaType: 17, //单证分类
            firstClass: 18, //单证类型
            secondClass: 19, //单证二级类型
            isValuable: 20, //单证是否有价
            operateType: 21, //单证状态
            classBigName: 35, //产品大类
            classSmallName: 36, //产品小类
            classTypeName: 37, //产品类型
            ValidStatus: 38, //有效状态
            VerifyStatus: 39, //审核状态
            AgreementCatalog: 40, //协议分类
            educationCode: 118, //学历/教育
            ReceiptType: 43, //回执状态
            BusinessNature: 44, //业务员类型
            AuditFlag: 45, //审核状态
            AuditreOpinion: 46, //审核意见
            IdentifyType: 47, //出险人证件类型
            AccidentType: 48, //出险类型
            commType: 49, //结算单类型
            status: 50, //结算单状态
            commStatus: 51, //结算状态
            bonusType: 52, //奖金类型
            LifeReport: 60, //人身险报表类型
            Race: 97, //民族
            ManagerDutyId: 98, //行政人员级别
            TechLevel: 99, //业务人员职级
            bonusType2: 105, //奖金类型2
            ComCodeMap: 110, //机构映射关系
            ComLevel: 111, //机构级别
            BusinessType: 112, //团队业务类型
            IsNot: 113, //是否
            ChannelType: 115, //产品渠道
            ApplyType: 116, //审核任务类型
            Sex: 117, //性别
            Places: 118, //学历
            JobGrade1: 119, //职级
            JobType: 120, //兼职/全职
            MaritalStatus: 121, //婚姻
            Relationship: 122, //关系
            ChannelQueryType: 123, //产品渠道
            ClassBigType: 124, //险种大类类型
            LocalType: 125, //户口类型
            political: 126, //政治面貌
            haveNot: 127, //有无
            btype: 128, //代理人业务渠道
            btypes: 129, //代理人业务渠道查询
            ComLevels: 130, //机构级别查询
            validStatusS: 131, //职位状态
            validStatusSA: 132, //在职离职
            bank: 133, //银行
            bigName: 900, //财险产品大类
            smallName: 901, //财险产品小类
            moneySuspiciousInd: 902, //反洗钱可疑交易特征
            businessBelong: 903, //业务归属
            businessFrom: 904, //业务来源
            moneyType: 905, //币别
            vehicleTypeDesc: 906, //交管车辆类型
            Job: 907, //职业
            insuredAddress: 908, //承保地区
            riskType: 909, //险别
            opposedMoney: 910, //反洗钱可疑交易特征
            professionBigCode: 911, //职业大类代码
            professionJobCode: 912, //职业工种代码
            agentJobGrade: 920, //业务员职级
            businessSectorType: 921, //团队业务部类型
            intermediaryName: 922, //中介名称
            assessmentType: 923, //考核指标类型
            payCycle: 924, //保费缴费周期
            payWay: 925, //保费缴费方式
            mainFlag: 926, //主/附险标志
            expenseCategory: 927, //费用类别
            unVerifyComCode: 928, //投保单免审核分公司
            EXCEPT_COM_CODE: 929, //不判断代理人类型的分公司
            examineId: 933, //审核岗位id
            idNumber: 934, //证件类型
            YBSL: 935, //银保税率
            budgettype: 936, //预算费用类型
            basenumtype: 937, //基数类型
            channel: 938, //渠道
            examineIdYB: 955, //审核岗位id
            examineIdYbAgs: 956, //审核岗位id
            ybAgentType: 957, //银保人员
            tdAgentType: 958, //同道人员
            cfAgentType: 959, //财富人员
            xxAgentType: 960, //线下代理人
            cxAgentType: 961, //创新渠道人员
        }
    }
}